### ISSUE TITLE
Use com.ninjasquad package instead of com.ninja_squad

### ISSUE THREAD

**Issue by sdeleuze** [Ninja-Squad/spring-rest-docs-kotlin#13]
Underscore in packages are pretty uncommon (I don't like them honestly) and that would be consistent with https://github.com/Ninja-Squad/springmockk.

**Comment by cexbrayat** [comment]
@sdeleuze I like how you consistently look at that first in a project 😆

**Comment by jnizet** [comment]
Thanks. Will change. We initially decided to go with ninja_squad because that's what was recommended to match a domain name with dashes (ninja-squad), but then decided that it didn't really matter. Don't know why I reused the underscore here.
Will change.
But eventually, it will be `org.springframework` anyway, right? :-) fingers crossed
